title: Srijita Karmakar
subtitle:  sometimes what's real is something you can't see
description: >- # this means to ignore newlines until "baseurl:"
  Now where does this go?
url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: About Me
      url: /about
    - text: Blog
      url: /blog

# Edit these details

author_logo: profile.png
author: Srijita Karmakar
author_bio: Life is a continuous learning process! 
            A very enthusiastic and dedicated undergrad, currently pursuing a B.Tech degree in mechanical engineering from IIT Madras. Versatile, quick to grasp and loves to collaborate, currently working on the mechanical and software aspect of robotics, hoping to make it big.
author_email: "srijita@ucsb.edu"
author_location: California, USA
typewrite-text: The eye is the window to the brain...

author_work_experiences:
            - company_name: iBot Club, Centre for Innovation
              company_logo: ib.png
              company_url: http://cfi.iitm.ac.in/wordpress/index.php/ibot-club/
              designation: iBot(Robotics) Club Head
              description: Managed and mentored various projects as well as conducted robotics oriented session with the aim of improving the tech culture in the institute.
              visibility: true
            - company_name: Ramakrishna Math, Chennai
              company_logo: ib.png
              company_url: https://chennaimath.org/
              designation: Robotics Intern
              description: Worked on 'Biley Bot', a lifelike, interactive humanoid robot of young Swami Vivekananda, soon to be displayed in Vivekanandar House Museum, Chennai. 
              visibility: true
            - company_name: Toyota Kirloskar Motor Pvt Ltd
              company_logo: ib.png
              company_url: https://en.wikipedia.org/wiki/Toyota_Kirloskar_Motor
              designation: Summer Engineering Intern
              description: Industrial internship with on-field experience from a reputed manufacturing factory. Experience on workshop floor included a project study on Backdoor Cushion Rubber Miss Elimination.
              visibility: true

author_education_details:
              - college_logo: ib.png
                college_name: Indian Institute of Technology, Madras
                college_url: https://www.iitm.ac.in/
                college_degree: Dual Degree (B.Tech in Mechanical Engineering + M.Tech in Robotics) 
                description: Bachelor of Technology in Mechanical Engineering & Inter Disciplinary Master of Technology in Robotics
                visibility: true
              - college_logo: ib.png
                college_name: Udacity
                college_url: https://www.udacity.com/course/robotics-software-engineer--nd209
                college_degree: Robotics Software Engineer Nanodegree 
                description: Programmed various robots in simulation and worked with Jetson TX2 hardware implementing various robotic algorithms(Localization, Mapping, SLAM, Path Planning and Navigation, 3D perception, Deep Learning, Manipulator Kinematics) and tools(ROS using python & C++, RViz, Gazebo and more).
                visibility: true

author_project_details:
              - project_thumbnail: ib.png
                project_title: ARTEMIS - Railroad Crack Detection Robot
                project_description: ARTEMIS is an autonomous robot that traverses inbetween the railway tracks, detects faults and sends the coordinates for further action to be taken.
                project_url: https://www.jamesdysonaward.org/2017/project/railroad-crack-detection-bot/
                visibility: true
              - project_thumbnail: ib.png
                project_title: Robotic Arm - Pick and Place
                project_description: The goal of the project is to solve is to simulate a robotic arm and perform a pick-and-place exercise very similar to Amazon Robotics Challenge.
                project_url: https://github.com/VihaanAkshaay/Project_Robo-ND_Robotic-Arm_Pick-And-Place
                visibility: true
              - project_thumbnail: ib.png
                project_title: 3D Perception Project
                project_description: The goal of this project is to program a PR2 to identify and acquire target objects from a cluttered space and place them in a bin. The project is based on the 'Stow Task' portion of Amazon's Robotics Challenge.
                project_url: https://github.com/VihaanAkshaay/Project_Robo-ND_3D-Perception-Project
                visibility: true
              - project_thumbnail: ib.png
                project_title: Robotic Arm - Pick and Place
                project_description: In a simulated environment, given camera input from a drone, the goal is to train a fully convoluted neural network to identify the location of a moving target and to control the drone to follow the same.
                project_url: https://github.com/VihaanAkshaay/Project_RoboND_Follow-Me
                visibility: true                

# social links
github_username:  VihaanAkshaay
linkedin_username: vihaanakshaayrajendiran
instagram_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )


# wakatime username (coding activity)
wakatime_username: VihaanAkshaay

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
formspree_email: johndoe@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-46783401-10

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true


# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'


# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build