title: Srijita Karmakar
subtitle:  sometimes what's real is something you can't see
description: >- # this means to ignore newlines until "baseurl:"
  PhD student at UCSB, Psychological and Brain Sciences Department
url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: About Me
      url: /about
    

# Edit these details

author_logo: profile.png
author: Srijita Karmakar
author_bio: I am a graduate student at the Department of Psychological and Brain Sciences, University of California, Santa Barbara. I am interested in exploring questions that can potentially allow a better understanding of vision and the brain's role in it. When I am not doing vision science or honing my computational skills, you would probably find me writing poetry, playing my guitar, or trekking Himalayan mountains.
author_email: "srijita@ucsb.edu"
author_location: California, USA
#typewrite-text: The eyes may be windows to the soul, but they surely are doors to the brain...
#hero_cover_img: cover.png

author_work_experiences:
            - company_name: University of California, Santa Barbara
              company_logo: ucsb.png
              company_url: https://www.ucsb.edu/
              designation: Graduate Teaching Assistant, Perception
              description: Fall 2022, was a teaching assistant to 100-odd undegraduate students. Duties included holding office hours. proctoring, and grading
              visibility: true
            - company_name: Indian Institute of Science Education and Reseach, Kolkata
              company_logo: iiserk.png
              company_url: https://www.iiserkol.ac.in/web/en/
              designation: Teaching Assistant, Cell Biology and Evolutionary Biology
              description: Fall 2021 and Spring 2022, duties involved proctoring, and grading
              visibility: true
            - company_name: Ek Pehal, IISER Kolkata
              company_logo: ekp.jpg
              company_url: https://sites.google.com/site/ekpehal2015/
              designation: Teaching Staff
              description: 2019-2022, volunteered with Ek Pehal, a student-led initiativen associated with my undergraduate institute campus, to teach young children from neigbouring localities
              visibility: true

author_education_details:
              - college_logo: ucsb.png
                college_name: University of California, Santa Barbara
                college_url: https://www.ucsb.edu/
                college_degree: Ongoing PhD 
                description: 2022-present, pursuing a PhD in the Dept. of Psychological and Brain Sciences at UCSB
                visibility: true
              - college_logo: iiserk.png
                college_name: Indian Institute of Science Education and Research, Kolkata
                college_url: https://www.iiserkol.ac.in/web/en/
                college_degree: Dual Degree (BS-MS in Life Sciences) 
                description: 2017-2022, earned Bachelors and Masters Degree in a 5-year Integrated program (GPA 9.46/10)
                visibility: true

              

author_project_details:
              - project_thumbnail: kd.png
                project_title: Effect of visual experience with face-masks on face perception during COVID-19
                project_description: 2021-2022, my Masters' Research Project focused on utilizing psychophysics and EEG to understand the effect of extensive usage of face-masks in light of COVID-19 on the perceptual abilities of human beings (VSS conference abstract linked below)
                project_url: https://doi.org/10.1167/jov.22.14.3243
                visibility: true
              - project_thumbnail: nma.png
                project_title: Reward and Emotion Interaction-an fMRI data analysis project
                project_description: Summer 2022, Neuromatch Academy Project wherein I was part of a team who worked to explore a link between reward processing and emotion with the help of human fMRI data
                project_url: https://docs.google.com/presentation/d/1HxTTPJLCty0zqCUq8xyeXwzgsiJ4ygy7LHVWC1x8uSs/edit?usp=sharing
                visibility: true
              - project_thumbnail: ma1.png
                project_title: Machine Learning and Network Analysis Course Project
                project_description: 2022, in this project I was part of a team and we used random forest classifier and PCA to extract meaningful information from a pre-recorded dataset
                #project_url: https://github.com/VihaanAkshaay/Project_Robo-ND_Robotic-Arm_Pick-And-Place
                visibility: true
              - project_thumbnail: langur.png
                project_title: Feeding Preference of Free-Raging Gray Langurs in an Urban Context
                project_description: Summer 2019, I was part of a team that explored the adaptive feeding behavior of primates in an urbanized setting (publication linked below)
                project_url: https://doi.org/10.3389/fpsyg.2021.649027
                visibility: true
              - project_thumbnail: mp.png
                project_title: Effect of Medicinal Drugs on Drosophila (wild-type and mutated)
                project_description: Summer 2018, I investigated whether medicinal drugs can rescue certain mutated fly lines 
                #project_url: https://github.com/VihaanAkshaay/Project_RoboND_Follow-Me
                visibility: true                

# social links
github_username:  srijitakarmakar
linkedin_username: srijitakarmakar
#instagram_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )


# wakatime username (coding activity)
#wakatime_username: VihaanAkshaay

# mailchimp embedded form url (newsletter):
#mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
#formspree_email: johndoe@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-46783401-10

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true


# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'


# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build